version: '3.9'
services:
  data_api:
    build: ./data/api
    ports:
      - "8000:8000"
    environment:
      - NPAIR_DB_URL=postgresql://admin:3Dgen_gltf@db/npair_db
      - TMDB_DB_URL=postgresql://admin:3Dgen_gltf@db/tmdb
    volumes:
      - ./data/storage:/data/storage
      - ./data/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
    depends_on:
      - db

db:
    image: postgres:14
    volumes:
      - ./data/storage/db:/var/lib/postgresql/data
      - ./logs:/app/logs
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    environment:
      POSTGRES_MULTIPLE_DATABASES: npair_db,tmdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3Dgen_gltf
