version: '3.8'

services:
  data_api:
    build: ./data/api
    ports:
      - "8000:8000"
    volumes:
      - .data/storage:/var/lib/postgresql/data
    environment:
      - DATABASE_URL=postgresql://admin:3Dgen_gltf@db/npair_db
    depends_on:
      - db

  model_api:
    build: ./model/api
    ports:
      - "8001:8001"
    depends_on:
      - db

  user_api:
    build: ./user/api
    ports:
      - "8002:8002"
    depends_on:
      - data_api
      - model_api

  db:
    build: ./data/sql
    volumes:
      - .data/storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: npair_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3Dgen_gltf

  tracking:
    build: ./model/tracking
    ports:
      - "5000:5000"
    depends_on:
      - db

  prometheus:
    build: ./user/monitoring/prometheus
    ports:
      - "9090:9090"

  grafana:
    build: ./user/monitoring/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  - .data/storage:
