version: '3.9'
services:
  data_api:
    build: ./data/api
    ports:
      - "8000:8000"
    environment:
      - NPAIR_DB_URL=postgresql://admin:3Dgen_gltf@db/npair_db
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=tmdb      
    volumes:
      - ./data/storage:/data/storage
      - ./data/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
    depends_on:
      - db
      - cassandra

  model_api:
    build: ./model/api
    ports:
      - "8001:8001"
    volumes:
      - ./data/storage:/data/storage
      - ./model/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
      - ./model/huggingface:/root/.cache/huggingface
      - ./model/u2net:/root/.u2net
    depends_on:
      - data_api
    runtime: nvidia # Enables GPU access

  user_api:
    build: ./user/api
    ports:
      - "8002:8002"
    volumes:
      - ./data/storage:/data/storage
      - ./user/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
    depends_on:
      - data_api
      - model_api

  db:
    image: postgres:14
    volumes:
      - ./data/storage/db:/var/lib/postgresql/data
      - ./logs:/app/logs
    environment:
      POSTGRES_DB: npair_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3Dgen_gltf

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./data/storage/cdb:/var/lib/cassandra
