version: '3.9'
services:
  data_api:
    build: ./data/api
    ports:
      - "8000:8000"
    environment:
      - NPAIR_DB_URL=postgresql://admin:3Dgen_gltf@db/npair_db
      - API_KEY=9831243-d1ff87804d4b3508285497c61
    volumes:
      - ./data/storage:/data/storage
      - ./data/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
    depends_on:
      - db

  model_api:
    build:
      context: ./model/api
      dockerfile: Dockerfile.cpu
    image: npair_model_api:cpu
    ports:
      - "8001:8001"
    environment:
      - NPAIR_DB_URL=postgresql://admin:3Dgen_gltf@db/npair_db
      - API_KEY=9831243-d1ff87804d4b3508285497c61
    volumes:
      - ./data/storage:/data/storage
      - ./model/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
      - ./model/huggingface:/root/.cache/huggingface
      - ./model/u2net:/root/.u2net
    depends_on:
      - data_api

  user_api:
    build: ./user/api
    ports:
      - "8002:8002"
    environment:
      - NPAIR_DB_URL=postgresql://admin:3Dgen_gltf@db/npair_db
      - API_KEY=9831243-d1ff87804d4b3508285497c61      
    volumes:
      - ./data/storage:/data/storage
      - ./user/api/pip_cache:/root/.cache/pip
      - ./logs:/app/logs
    depends_on:
      - data_api
      - model_api

  db:
    image: postgres:14
    volumes:
      - ./data/storage/db:/var/lib/postgresql/data
      - ./logs:/app/logs
    environment:
      POSTGRES_DB: npair_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3Dgen_gltf

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=critical
      - GF_SMTP_ENABLED=false
      - GF_ALERTING_ERROR_OR_TIMEOUT=keep_state
      - GF_ALERTING_NODATA_OR_NULLVALUES=keep_state
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=
      - GF_INSTALL_PLUGINS=
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PLUGIN_XYCHART=false
    logging:
      driver: "none"
    depends_on:
      - db
