name: Build, Test, and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push npair_user_api image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/npair_user_api:latest
        context: ./user/api
        file: ./user/api/Dockerfile

    - name: Build and push npair_model_api image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/npair_model_api:cpu
        context: ./model/api
        file: ./model/api/Dockerfile.cpu

    - name: Build and push npair_data_api image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/npair_data_api:latest
        context: ./data/api
        file: ./data/api/Dockerfile

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose






